Benefit.Web/Areas/Admin/Controllers/AdminStuffController.cs
using System.Web.Mvc;
using Benefit.Common.Constants;
using Benefit.Services;
using Benefit.Services.Admin;
using Benefit.Web.Areas.Admin.Controllers.Base;
using Benefit.Web.Helpers;
using System.Web;
using Benefit.Domain.Models;
using Benefit.Web.Filters;
using System.Collections;

namespace Benefit.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = DomainConstants.SuperAdminRoleName)]
    public class AdminStuffController : AdminController
    {
        ScheduleService ScheduleService = new ScheduleService();

        //todo: change controller name
        //
        // GET: /Admin/AdminStuff/
        public ActionResult Index()
        {
            return View();
        }

        [FetchSeller]
        public ActionResult GenerateSitemap()
        {
            var siteMapHelper = new SiteMapHelper();
            siteMapHelper.Generate(Url, Request.Url.Scheme + "://" + Request.Url.Host, true, (ViewBag.Seller as Seller));
            TempData["SuccessMessage"] = "Файл sitemap.xml згенеровано";
            return RedirectToAction("Index");
        }

        public ActionResult ClearCategoriesCache()
        {
            HttpRuntime.Cache.Remove("Categories");
            var staleItem = Url.Action("Index", "Home", new
            {
                area = string.Empty
            });
            Response.RemoveOutputCacheItem(staleItem);
            IDictionaryEnumerator enumerator = HttpRuntime.Cache.GetEnumerator();
            while (enumerator.MoveNext())
            {
                string key = (string)enumerator.Key;
                if (key.Contains("Seller"))
                {
                    HttpRuntime.Cache.Remove(key);
                }
            }
            TempData["SuccessMessage"] = "Кеш категорій очищено";
            return RedirectToAction("Index");
        }
    }
}

Benefit.Web/Controllers/ScheduleController.cs
using Benefit.Domain.DataAccess;
using Benefit.Domain.Models;
using Benefit.Services.Domain;
using Benefit.Web.Filters;
using Benefit.Web.Helpers;
using System;
using System.IO;
using System.Linq;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Mvc;
using Benefit.Services.Import;

namespace Benefit.Web.Controllers
{
    [CustomKeyAuth]
    public class ScheduleController : Controller
    {
        public ActionResult ProcessImportTasks()
        {
            using (var db = new ApplicationDbContext())
            {
                var importTasks =
                db.ExportImports
                    .Include(entry => entry.Seller)
                    .Include(entry => entry.Seller.MappedCategories)
                    .Where(entry => entry.IsActive && entry.SyncType != SyncType.YmlExport && entry.SyncType != SyncType.YmlExport).ToList();
                Task.Run(() =>
                {
                    foreach (var importTask in importTasks)
                    {
                        if (importTask.LastSync.HasValue && (DateTime.UtcNow - importTask.LastSync.Value).TotalDays < importTask.SyncPeriod)
                        {
                            continue;
                        }
                        ImportServiceFactory.GetImportServiceInstance(importTask.SyncType).Import(importTask.Id);
                    }
                });
            }
            return Content("Ok");
        }
        public ActionResult GenerateSellerReport(int? year = null, int? month = null, string sellerId = null)
        {
            var sellerReportService = new SellerReportService();
            year = year ?? DateTime.Now.Year;
            month = month ?? (DateTime.Now.Month - 1 == 0 ? 12 : DateTime.Now.Month - 1);
            var startDate = new DateTime(year.Value, month.Value, 1, 0, 0, 0);
            var endDate = new DateTime(year.Value, month.Value, DateTime.DaysInMonth(year.Value, month.Value), 23, 59, 59);
            var originalDirectory = AppDomain.CurrentDomain.BaseDirectory.Replace(@"bin\Debug\", string.Empty);
            var reportsPath = Path.Combine(originalDirectory, "Reports");
            using (var db = new ApplicationDbContext())
            {
                var sellerIds = db.Orders
                    .Where(entry => entry.Time > startDate && entry.Time < endDate)
                    .Select(entry => entry.SellerId).Distinct();
                if (sellerId != null)
                {
                    sellerIds = sellerIds.Where(entry => entry == sellerId);
                }
                foreach (var seller_id in sellerIds)
                {
                    if (db.SellerReports.Any(entry => entry.SellerId == seller_id && entry.Month == month && entry.Year == year))
                        continue;
                    var bytes = sellerReportService.GenerateSellerReport(seller_id, startDate, endDate);
                    var reportPath = Path.Combine(reportsPath, seller_id);
                    if (!Directory.Exists(reportPath))
                    {
                        Directory.CreateDirectory(reportPath);
                    }
                    System.IO.File.WriteAllBytes(
                        Path.Combine(reportPath, string.Format("{0}-{1}-{2}.xls", year.Value, month.Value, DateTime.Now.ToString("yyyyMMddhhmm"))), bytes);
                    var sellerReport = new SellerReport()
                    {
                        Date = DateTime.Now,
                        FileUrl = string.Format("{0}-{1}-{2}.xls", year.Value, month.Value, DateTime.Now.ToString("yyyyMMddhhmm")),
                        Id = Guid.NewGuid().ToString(),
                        SellerId = seller_id,
                        Month = month.Value,
                        Year = year.Value
                    };
                    db.SellerReports.Add(sellerReport);
                }
                db.SaveChanges();
            }
            return Content("Ok");
        }
        public ActionResult GenerateExportFiles(string exportId = null)
        {
            var exportService = new ExportService();
            var originalDirectory = AppDomain.CurrentDomain.BaseDirectory.Replace(@"bin\Debug\", string.Empty);
            using (var db = new ApplicationDbContext())
            {
                var exports = db.ExportImports.Where(entry => entry.SyncType == SyncType.YmlExport || entry.SyncType == SyncType.YmlExportEpicentr || entry.SyncType == SyncType.YmlExportProm).ToList();
                if (exportId != null)
                {
                    exports = exports.Where(entry => entry.Id == exportId).ToList();
                }
                foreach (var export in exports)
                {
                    var destPath = Path.Combine(originalDirectory, "Export", export.Name);
                    var isExists = Directory.Exists(destPath);
                    if (!isExists)
                    {
                        Directory.CreateDirectory(destPath);
                    }
                    destPath = Path.Combine(destPath, "index.xml");
                    if (exportService.Export(export.Id, destPath) == null)
                    {
                        return Content("Export file was not generated");
                    }
                }
            }
            return Content("Export files generated");
        }

        public ActionResult GenerateSiteMap()
        {
            var siteMapHelper = new SiteMapHelper();
            siteMapHelper.Generate(Url, Request.Url.Scheme + "://" + Request.Url.Host);
            return Content("Ok");
        }
    }
}

Benefit.Web/Areas/Admin/Views/AdminStuff/BonusesCalculation.cshtml
@model Benefit.DataTransfer.ViewModels.ProcessBonusesViewModel

@{
    ViewBag.Title = "Результати розрахунку";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@Html.Partial("_BonusesCalculationPartial", Model)

Benefit.Web/Areas/Admin/Views/AdminStuff/BonusesCalculationError.cshtml
Під час розрахунку відбулася помилка, але хвилюватись не потрібно, все буде добре! Просто нагодуйте розробнка печеньками і він все виправить :)

Benefit.Web/Areas/Admin/Views/AdminStuff/Index.cshtml
@using Benefit.Services
@{
    ViewBag.Title = "VIP функції";
}

<fieldset>
    <legend>
        SEO
    </legend>
    <a class="btn btn-info" href="@Url.Action("GenerateSitemap", "AdminStuff")">Згенерувати sitemap.xml</a>
</fieldset>
<fieldset>
    <legend>
        Запустити імпорт
    </legend>
    <a class="btn btn-info" href="@Url.Action("ProcessImportTasks", "Schedule", new {key = SettingsService.ScheduleKey, area = string.Empty})">Імпорт</a>
</fieldset>
<fieldset>
    <legend>
        Очистити кеш категорій
    </legend>
    <a class="btn btn-info" href="@Url.Action("ClearCategoriesCache", "AdminStuff")">Очистити кеш</a>
</fieldset>
<fieldset>
    <legend>
        Згенерувати рекомендовані та нові товари
    </legend>
    <a class="btn btn-info" target="_blank" href="@string.Format("{0}/Schedule/FetchFeaturedProducts?key={1}", SettingsService.BaseApiHostName, SettingsService.ScheduleKey)">Згенерувати</a>
</fieldset>
<fieldset>
    <legend>
        Синхронізувати замовлення з Розетка
    </legend>
    <a class="btn btn-info" target="_blank" href="@string.Format("{0}/Schedule/ProcessMarketplaceOrders?key={1}", SettingsService.BaseApiHostName, SettingsService.ScheduleKey)">Синхронізувати</a>
</fieldset>
@*<fieldset>
        <legend>
            Термінація
        </legend>
        <a class="btn btn-info" href="@Url.Action("TerminateNonActivePartners", "AdminStuff")" onclick="$(this).attr('disabled', 'disabled');">Термінація користувачів</a>
    </fieldset>*@
@*<fieldset>
        <legend>
            Чат
        </legend>
        <a class="btn btn-info" href="@Url.Action("ClearChat", "AdminStuff")">Очистити чат</a>
    </fieldset>*@

Benefit.Web/Areas/Admin/Views/AdminStuff/_BonusesCalculationPartial.cshtml
@model Benefit.DataTransfer.ViewModels.ProcessBonusesViewModel

<h2>Результати розрахунку</h2>

<fieldset>
    <legend>Загальні показники</legend>
    <table>
        <tr>
            <td>
                <strong>
                    Кількість партнерів, які заробили бали:
                </strong>
            </td>
            <td>
                @Model.ActiveBuyersCount
            </td>
        </tr>
        <tr>
            <td>
                <strong>
                    Загальная кількість нарахованих персональних бонусів:
                </strong>
            </td>
            <td>
                @Model.PersonalBonusesAccrued
            </td>
        </tr>
    </table>
</fieldset>
<fieldset>
    <legend>Бонуси наставника</legend>
    <table>
        <tr>
            <th>Імя</th>
            <th>Кількість бонусів</th>
        </tr>
        @foreach (var partner in Model.Partners)
        {
            <tr>
                <td>@partner.User.FullName</td>
                <td>@partner.BonusesReckoned</td>
            </tr>
        }
    </table>
</fieldset>
<br />
<fieldset>
    <legend>Бонуси VIP</legend>
    <table>
        <tr>
            <th>Імя</th>
            <th>Кількість бонусів</th>
        </tr>
        @foreach (var partner in Model.VipPartners)
        {
            <tr>
                <td>@partner.User.FullName</td>
                <td>@partner.BonusesReckoned</td>
            </tr>
        }
    </table>
</fieldset>