Benefit.Web/Controllers/CartController.cs
using Benefit.Common.Constants;
using Benefit.Common.Extensions;
using Benefit.DataTransfer.ViewModels;
using Benefit.Domain.DataAccess;
using Benefit.Domain.Models;
using Benefit.Services;
using Benefit.Services.Cart;
using Benefit.Services.Domain;
using Benefit.Web.Filters;
using Benefit.Web.Helpers;
using Microsoft.AspNet.Identity;
using NLog;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Benefit.Web.Controllers
{
    public class CartController : Controller
    {
        public OrderService OrderService = new OrderService();
        public UserService UserService = new UserService();
        private static Logger _logger = LogManager.GetCurrentClassLogger();

        [FetchCategories(Order = 1)]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CheckEnaughBonuses(double sum)
        {
            var user = UserService.GetUser(User.Identity.GetUserId());
            var result = .0;
            if (user.BonusAccount >= sum)
            {
                result = sum;
            }
            return Json(new
            {
                total = result
            }, JsonRequestBehavior.AllowGet);
        }

        //[HttpGet]
        //public ActionResult CheckSeller(string sellerId)
        //{
        //    return Json(Cart.CurrentInstance.Order.SellerId != null && Cart.CurrentInstance.Order.SellerId != sellerId, JsonRequestBehavior.AllowGet);
        //}

        public ActionResult AddProduct(OrderProduct product, string sellerId)
        {
            var productsNumber = Cart.CurrentInstance.AddProduct(product, sellerId);
            return Json(productsNumber);
        }

        public ActionResult UpdateQuantity(string productId, string sellerId, double amount)
        {
            var productsNumber = Cart.CurrentInstance.UpdatePoductQuantity(productId, sellerId, amount);
            return Json(productsNumber);
        }

        public ActionResult RemoveProduct(string productId, string sellerId)
        {
            var productsNumber = Cart.CurrentInstance.RemoveProduct(sellerId, productId);
            return Json(productsNumber);
        }

        [HttpPost]
        public ActionResult CompleteOrder(List<OrderProduct> orderProducts, string sellerId)
        {
            Cart.CurrentInstance.ClearSellerOrder(sellerId);
            foreach (var orderProduct in orderProducts)
            {
                Cart.CurrentInstance.AddProduct(orderProduct, sellerId);
            }
            var orderSummary = Cart.CurrentInstance.GetOrderProductsCountAndPrice();
            return Json(new { redirectUrl = Url.Action("order", "cart", new { id = sellerId }), orderSummary.ProductsNumber, orderSummary.Price });
        }

        [FetchSeller(Order = 0)]
        [FetchCategories(Order = 1)]
        public ActionResult Order(string id)
        {
            var model = new CompleteOrderViewModel
            {
                SellerId = id,
                Order = Cart.CurrentInstance.Orders.FirstOrDefault(entry => entry.SellerId == id)
            };
            var domainSeller = ViewBag.Seller as Seller;
            ViewResult view = null;
            if (domainSeller != null)
            {
                var layoutName = string.Format("~/Views/SellerArea/{0}/Cart.cshtml",
                    domainSeller.EcommerceTemplate.GetValueOrDefault(SellerEcommerceTemplate.Default));
                view = View(layoutName, model);
            }
            else
            {
                view = View(model);
            }
            if (model.Order == null)
            {
                return view;
            }

            using (var db = new ApplicationDbContext())
            {
                var seller = db.Sellers
                    .Include(entry => entry.Promotions)
                    .Include(entry => entry.AssociatedSellers)
                    .FirstOrDefault(entry => entry.Id == id);
                var userId = User.Identity.GetUserId();
                if (seller == null)
                {
                    throw new HttpException(404, "Not found");
                }

                //promotions
                var now = DateTime.UtcNow;
                var currentPromotion =
                    seller.Promotions.FirstOrDefault(
                        entry => entry.Start < now && entry.End > now && !entry.IsBonusDiscount && entry.IsActive);

                if (currentPromotion != null)
                {
                    if (currentPromotion.StartTime.HasValue && currentPromotion.EndTime.HasValue)
                    {
                        currentPromotion.StartTimeDt =
                            DateTime.Now.ToLocalTime().StartOfDay().AddHours(currentPromotion.StartTime.Value);
                        currentPromotion.EndTimeDt =
                            DateTime.Now.ToLocalTime().StartOfDay().AddHours(currentPromotion.EndTime.Value);

                        if (DateTime.Now.ToLocalTime() > currentPromotion.StartTimeDt &&
                            DateTime.Now.ToLocalTime() < currentPromotion.EndTimeDt)
                        {
                            model.Order.Sum = model.Order.GetOrderSum();
                            if (model.Order.Sum >= currentPromotion.DiscountFrom)
                            {
                                model.Order.SellerDiscount = currentPromotion.IsValuePercent
                                    ? model.Order.Sum * currentPromotion.DiscountValue / 100
                                    : currentPromotion.DiscountValue;
                                model.Order.SellerDiscountName = currentPromotion.Name;
                            }
                        }
                    }
                    else
                    {
                        model.Order.Sum = model.Order.GetOrderSum();
                        if (model.Order.Sum >= currentPromotion.DiscountFrom)
                        {
                            model.Order.SellerDiscount = currentPromotion.IsValuePercent
                                ? model.Order.Sum * currentPromotion.DiscountValue / 100
                                : currentPromotion.DiscountValue;
                            model.Order.SellerDiscountName = currentPromotion.Name;
                        }
                    }
                }

                var sellersInOrder = model.Order.OrderProducts.Select(entry => entry.SellerId).Distinct().Count();
                model.ShippingMethods = db.ShippingMethods.Where(entry => entry.SellerId == id).ToList();
                if (sellersInOrder > 1 && seller.AssociatedSellers.Any())
                {
                    var associatedSellerIds = seller.AssociatedSellers.Select(ac => ac.Id).ToList();
                    var associatedShippingMethods = db.ShippingMethods.Where(entry => associatedSellerIds.Contains(entry.SellerId)).ToList();
                    model.ShippingMethods = model.ShippingMethods
                        .Intersect(associatedShippingMethods, new ShippingMethodComparer()).ToList();
                }
                if (userId != null)
                {
                    model.Addresses = db.Addresses.Include(entry => entry.Region).Where(entry => entry.UserId == userId)
                        .ToList();
                }
                if (seller.IsPrePaidPaymentActive)
                {
                    model.PaymentTypes.Add(PaymentType.PrePaid);
                }

                if (seller.IsPostPaidPaymentActive)
                {
                    model.PaymentTypes.Add(PaymentType.PostPaid);
                }

                if (seller.IsCashPaymentActive)
                {
                    model.PaymentTypes.Add(PaymentType.Cash);
                }

                if (seller.IsAcquiringActive)
                {
                    model.PaymentTypes.Add(PaymentType.Acquiring);
                }

                if (seller.IsBonusesPaymentActive)
                {
                    model.PaymentTypes.Add(PaymentType.Bonuses);
                }

                if (sellersInOrder > 1 && seller.AssociatedSellers.Any())
                {
                    if (!seller.AssociatedSellers.Any(entry => entry.IsPrePaidPaymentActive))
                    {
                        model.PaymentTypes.Remove(PaymentType.PrePaid);
                    }

                    if (!seller.AssociatedSellers.Any(entry => entry.IsPostPaidPaymentActive))
                    {
                        model.PaymentTypes.Remove(PaymentType.PostPaid);
                    }

                    if (!seller.AssociatedSellers.Any(entry => entry.IsCashPaymentActive))
                    {
                        model.PaymentTypes.Remove(PaymentType.Cash);
                    }

                    if (!seller.AssociatedSellers.Any(entry => entry.IsAcquiringActive))
                    {
                        model.PaymentTypes.Remove(PaymentType.Acquiring);
                    }

                    if (!seller.AssociatedSellers.Any(entry => entry.IsBonusesPaymentActive))
                    {
                        model.PaymentTypes.Remove(PaymentType.Bonuses);
                    }
                }
            }

            return view;
        }

        [FetchSeller(Order = 0)]
        [FetchCategories(Order = 1)]
        public ActionResult OrderCompleted(string number)
        {
            var seller = ViewBag.Seller as Seller;
            if (seller != null)
            {
                if (seller != null)
                {
                    var layoutName = string.Format("~/Views/SellerArea/{0}/OrderCompleted.cshtml",
                        seller.EcommerceTemplate.GetValueOrDefault(SellerEcommerceTemplate.Default));
                    return View(layoutName, model: number);

Benefit.Web/Controllers/SearchController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Benefit.Common.Constants;
using Benefit.DataTransfer.JSON;
using Benefit.DataTransfer.ViewModels;
using Benefit.DataTransfer.ViewModels.NavigationEntities;
using Benefit.Domain.Models;
using Benefit.Services;
using Benefit.Web.Filters;
using Benefit.Web.Helpers;

namespace Benefit.Web.Controllers
{
    public class SearchController : Controller
    {
        SearchService SearchService = new SearchService();
      
        public ActionResult SearchWords(string query, string sellerId = null)
        {
            var searchResult = SearchService.SearchKeyWords(query, sellerId);
            var result = new AutocompleteSearch
            {
                query = query,
                suggestions = searchResult.Select(entry => new ValueData()
                {
                    value = entry,
                    data = entry
                }).ToArray()
            };
            return Json(result,
                JsonRequestBehavior.AllowGet);
        }

        [FetchSeller(Order = 0)]
        [FetchCategories(Order = 1)]
        public ActionResult Index(string term, string options, string searchSellerId)
        {
            searchSellerId = searchSellerId == string.Empty ? null : searchSellerId;
            var result = SearchService.SearchProducts(term, options, 0, searchSellerId);
            result.SellerId = searchSellerId;
            if (!string.IsNullOrEmpty(searchSellerId))
            {
                var seller = ViewBag.Seller as Seller;
                var viewName = string.Format("~/Views/SellerArea/{0}/ProductsCatalog.cshtml",
                    seller.EcommerceTemplate.GetValueOrDefault(SellerEcommerceTemplate.Default));
                return View(viewName, new ProductsViewModel
                {
                    Items = result.Products,
                    PagesCount = result.PagesCount,
                    ProductParameters = result.ProductParameters,
                    Category = new CategoryVM()
                    {
                        Name = "Пошук: " + term,
                        UrlName = "search",
                        Description = string.Format("Результати пошуку по запиту '{0}'", result.Term)
                    },
                    Breadcrumbs = new BreadCrumbsViewModel()
                    {
                        Categories = new Dictionary<CategoryVM, List<CategoryVM>>()
                        {
                            {
                                new CategoryVM()
                                {
                                    Name = "Пошук"
                                },
                                null
                            }
                        }
                    }
                });
            }
            return View(result);
        }

        public ActionResult GetProducts(string term, string options, int page, SellerEcommerceTemplate? layout)
        {
            var result = SearchService.SearchProducts(term, options, ListConstants.DefaultTakePerPage * page);
            var templateName = "~/Views/Catalog/_ProductPartial.cshtml";
            if (layout.HasValue)
            {
                templateName = string.Format("~/Views/SellerArea/{0}/_ProductPartial.cshtml", layout.ToString());
            }
            var productsHtml = string.Join("", result.Products.Take(ListConstants.DefaultTakePerPage).Select(entry => ControllerContext.RenderPartialToString(templateName, entry)));
            return Json(new { number = result.Products.Count, products = productsHtml }, JsonRequestBehavior.AllowGet);
        }
    }
}

Benefit.Web/Views/Search/Index.cshtml
@using System.Web.Mvc.Html
@using Benefit.Common.Constants
@using Benefit.DataTransfer.ViewModels
@using Benefit.Domain.Models
@using Benefit.Services.Domain
@model Benefit.Domain.Models.Search.SearchResult

@{
    ViewBag.Title = string.Format("Результати пошуку '{0}'", Model.Term);
}
@section scripts
{
    <script> 
        var reloadOnProductAdd = false;
        var productOptionsUrl = '@Url.Action("GetProductOptions", "Tovar")';
        var productVariantsUrl = '@Url.Action("GetProductVariants", "Tovar")';
        var addToCartUrl = '@Url.Action("AddProduct", "Cart")';
        var getProductsUrl = '@Url.Action("GetProducts", "Search")';
        var addToFavoritesUrl =
            '@Html.Raw(Url.Action("AddToFavorites", "Tovar", new {returnUrl = Request.Url.PathAndQuery}))';
        var removeFromFavoritesUrl = '@Url.Action("RemoveFromFavorites", "Tovar")';
        var showMessagePopupUrl = '@Url.Action("ShowMessagePopup", "Home")';
        var hasCategory = true;
        var categoryId = "";
        var sellerId ="";
        var categoryUrlName = 'search';
        var pagesCount = parseInt('@Model.PagesCount');
        var takePerPage = parseInt('@ListConstants.DefaultTakePerPage');
        var term = '@Model.Term';
    </script>
    <script src="~/Scripts/v3/products.js" defer></script>
    <script src="~/Scripts/v3/product-filters.js" defer></script>
}

<div class="wraps hover_shine" id="content">
    <!--title_content-->
    <div class="top_inner_block_wrapper maxwidth-theme" style="height: 80px;">
        <section class="page-top maxwidth-theme ">
            @Html.Partial("_BreadcrumbsPartial", new BreadCrumbsViewModel()
            {
                Page = new InfoPage()
                {
                    Name = "Пошук"
                }
            })
            <div class="page-top-main">
                Результати пошуку запиту <strong class="bigger-125">"@Model.Term"</strong>
            </div>
        </section>
    </div>

    <div class="wrapper_inner no-padding-top">
        <div class="right_block  wide_N">
            <div class="middle ">
                <div class="container">
                    <div class="right_block1 clearfix catalog vertical" id="right_block_ajax">
                        <div class="js_filter filter_horizontal">
                            <div class="bx_filter bx_filter_vertical"></div>
                        </div>
                        <div class="inner_wrapper">
                            <div class="adaptive_filter margin-bottom-5">
                                <a class="filter_opener">
                                    <i class="fa fa-filter black"></i>
                                    <span>Фільтри та сортування</span>
                                </a>
                            </div>
                            <div class="sections_wrapper">
                                <div class="list items">
                                    <div class="row margin0 products-wrapper">
                                        @foreach (var product in Model.Products.Take(ListConstants.DefaultTakePerPage))
                                        {
                                            @Html.Partial("~/Views/Catalog/_ProductPartial.cshtml", product)
                                        }
                                    </div>
                                </div>
                                <div class="bottom_nav margin-top-20">
                                    @if (Model.Products.Count > ListConstants.DefaultTakePerPage)
                                    {
                                        <div class="ajax_load_btn" data-page="1">
                                            <span class="more_text_ajax">Показати ще</span>
                                        </div>
                                    }
                                    @if (Model.PagesCount > 1)
                                    {
                                        <div class="pagination-wrap">
                                            <ul class="pagination no-list-style">
                                                <li class="page_item" data-page="0" style="display: none;">
                                                    <a class="page_link paging prev" href="#" data-page="0"><<</a>
                                                </li>
                                                <li class="page_item active" data-page="0">
                                                    <a class="page_link paging dark_link" href="#" data-page="0">1</a>
                                                </li>
                                                @for (int i = 2; i <= Model.PagesCount; i++)
                                                {
                                                    <li class="page_item">
                                                        <a class="page_link paging dark_link" href="#" data-page="@(i - 1)">@i</a>
                                                    </li>
                                                }
                                                <li class="page_item" data-page="1">
                                                    <a class="page_link paging next dark_link" href="#" data-page="1">>></a>
                                                </li>
                                            </ul>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="left_block">
            @if (Model.ProductParameters.Any())
            {
                @Html.Partial("~/Views/Catalog/_ProductFilters.cshtml", Model.ProductParameters)
            }
        </div>
    </div>
</div>