Benefit.Web/Areas/Admin/Controllers/ImportExportController.cs
using Benefit.Common.Constants;
using Benefit.Domain.DataAccess;
using Benefit.Domain.Models;
using Benefit.Services;
using Benefit.Services.Domain;
using NLog;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Benefit.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = DomainConstants.AdminRoleName + ", " + DomainConstants.SellerRoleName + ", " + DomainConstants.SellerModeratorRoleName)]
    public class ImportExportController : Controller
    {
        ProductsService ProductService = new ProductsService();
        EmailService EmailService = new EmailService();
        ExportService ImportService = new ExportService();
        private static Logger _logger = LogManager.GetCurrentClassLogger();

        public ActionResult Index()
        {
            using (var db = new ApplicationDbContext())
            {
                var seller = db.Sellers.FirstOrDefault(entry => entry.Id == Seller.CurrentAuthorizedSellerId);
                return View(seller);
            }
        }

        [HttpGet]
        public ActionResult GetImportTaskStatus(string sellerId, SyncType type)
        {
            using (var db = new ApplicationDbContext())
            {
                var importTask = db.ExportImports.FirstOrDefault(entry => entry.SellerId == sellerId && entry.SyncType == type);
                if (importTask != null)
                {
                    if (importTask.IsImport)
                    {
                        return Json(new { status = (int)ImportStatus.Pending }, JsonRequestBehavior.AllowGet);
                    }
                    return Json(new { status = (importTask.LastUpdateStatus.Value ? 1 : 0), message = importTask.LastUpdateMessage }, JsonRequestBehavior.AllowGet);
                }
                return new HttpNotFoundResult();
            }
        }

        public ActionResult Status()
        {
            using (var db = new ApplicationDbContext())
            {
                var importTasks = db.ExportImports
                    .Include(entry => entry.Seller)
                    .Where(entry => entry.SellerId != null)
                    .OrderByDescending(entry => entry.IsActive)
                    .ThenByDescending(entry => entry.LastSync).ToList();
                foreach (var task in importTasks)
                {
                    if (task.IsActive)
                    {
                        if (DateTime.Now - task.LastSync < TimeSpan.FromDays(3) && task.LastUpdateStatus.GetValueOrDefault(false))
                        {
                            task.Status = ImportStatus.Success;
                        }
                        else
                        {
                            task.Status = ImportStatus.Error;
                        }
                    }
                }
                return View(importTasks);
            }
        }

        public ActionResult Exports()
        {
            using (var db = new ApplicationDbContext())
            {
                var exports = db.ExportImports
                    .Include(entry => entry.Seller)
                    .Where(entry => entry.SyncType == SyncType.YmlExport || entry.SyncType == SyncType.YmlExportEpicentr || entry.SyncType == SyncType.YmlExportProm).ToList();

                return View(exports);
            }
        }

        public ActionResult CreateOrUpdateExport(string name, SyncType SyncType)
        {
            using (var db = new ApplicationDbContext())
            {
                if (string.IsNullOrEmpty(name))
                {
                    TempData["ErrorMessage"] = "Назва не може бути порожньою";
                }
                else if (db.ExportImports.Any(entry => entry.Name == name)) 
                {
                    TempData["ErrorMessage"] = "Експорт з такою назвою вже існує";
                }
                else
                {
                    var export = new ExportImport()
                    {
                        Id = Guid.NewGuid().ToString(),
                        Name = name,
                        SyncType = SyncType,
                        IsActive = true
                    };
                    db.ExportImports.Add(export);
                    db.SaveChanges();
                }
                return RedirectToAction("Exports");
            }
        }

        public ActionResult DeleteExport(string id)
        {
            using (var db = new ApplicationDbContext())
            {
                var export = db.ExportImports.Include(entry => entry.ExportProducts).FirstOrDefault(entry => entry.Id == id);
                if (export != null)
                {
                    db.ExportProducts.RemoveRange(export.ExportProducts);
                    db.ExportCategories.RemoveRange(export.ExportCategories);
                    db.ExportImports.Remove(export);
                }
                db.SaveChanges();
                return RedirectToAction("Exports");
            }
        }

        public ActionResult GetImportLinkForm(int number, string value)
        {
            return PartialView("_LinkForm", new KeyValuePair<int, string>(number, value));
        }

        public ActionResult GetImportForm(SyncType syncType)
        {
            using (var db = new ApplicationDbContext())
            {
                var newId = Guid.NewGuid().ToString();
                var importTask =
                    db.ExportImports
                    .Include(entry => entry.Links)
                    .FirstOrDefault(
                        entry => entry.SellerId == Seller.CurrentAuthorizedSellerId && entry.SyncType == syncType) ?? new ExportImport()
                        {
                            Id = newId,
                            IsActive = false,
                            IsImport = false,
                            SyncType = syncType,
                            FileUrl = string.Format("https://benefit.ua/export?id={0}", newId),
                            SellerId = Seller.CurrentAuthorizedSellerId,
                            Links = new List<Link>()
                        };

                var updateFrequency = new List<SelectListItem>()
                {
                    new SelectListItem() { Text = "Щоденно", Value = 1.ToString()},
                    new SelectListItem() { Text = "Раз в 3 дні", Value = 3.ToString()},
                    new SelectListItem() { Text = "Раз в тиждень", Value = 7.ToString()},
                    new SelectListItem() { Text = "Раз в місяць", Value = 30.ToString()}
                };
                ViewBag.SyncPeriod = new SelectList(updateFrequency, "Value", "Text", importTask.SyncPeriod.ToString());
                var currencies =
                   db.Currencies.Where(entry => entry.Provider == CurrencyProvider.PrivatBank).OrderBy(entry => entry.Id).ToList();
                ViewBag.DefaultCurrencyId = new SelectList(currencies, "Id", "ExpandedName", importTask.DefaultCurrencyId);
                return PartialView("_ImportForm", importTask);
            }
        }

        [HttpPost]
        public ActionResult CreateOrUpdate(ExportImport exportImport)
        {
            using (var db = new ApplicationDbContext())
            {
                if (exportImport.FileUrl == null)
                {
                    TempData["ErrorMessage"] = "Url має бути заповнено";
                    return RedirectToAction("Index");
                }
                else
                {
                    var import = db.ExportImports.Find(exportImport.Id);
                    if (import == null)
                    {
                        import = exportImport;
                        db.ExportImports.Add(import);
                    }
                    else
                    {
                        db.Entry(import).State = EntityState.Modified;
                    }
                    import.IsImport = exportImport.IsImport;
                    import.IsActive = exportImport.IsActive;
                    import.FileUrl = exportImport.FileUrl;
                    import.SyncPeriod = exportImport.SyncPeriod;
                    import.DefaultCurrencyId = exportImport.DefaultCurrencyId;

                    db.Links.RemoveRange(db.Links.Where(entry => entry.ExportImportId == import.Id));
                    db.SaveChanges();
                    if (exportImport.Links != null && exportImport.Links.Any())
                    {
                        foreach (var link in exportImport.Links)
                        {
                            link.Id = Guid.NewGuid().ToString();
                            link.ExportImportId = import.Id;
                            db.Links.Add(link);
                        }
                    }
                }
                db.SaveChanges();
                TempData["SuccessMessage"] = "Дані імпорту/експорту оновлено";
                return RedirectToAction("Index");
            }
        }

        public ActionResult UploadExcelFile(string sellerUrlName, HttpPostedFileBase import, HttpPostedFileBase images)
        {
            using (var db = new ApplicationDbContext())
            {
                if (import == null || import.ContentLength == 0)
                {
                    TempData["ErrorMessage"] = "Невірно вибраний файл імпорту";
                }
                else
                {
                    var originalDirectory = AppDomain.CurrentDomain.BaseDirectory.Replace(@"bin\Debug\", string.Empty);
                    var ftpDirectory = new DirectoryInfo(originalDirectory).FullName;
                    var sellerPath = Path.Combine(ftpDirectory, "FTP", "LocalUser", sellerUrlName);
                    var imagesPath = Path.Combine(sellerPath, "images");
                    if (!Directory.Exists(sellerPath))
                    {

Benefit.Web/Controllers/ExportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Benefit.Domain.DataAccess;
using Benefit.Domain.Models;
using Benefit.Services.Domain;

namespace Benefit.Web.Controllers
{
    public class ExportController : Controller
    {
        ExportService ImportExportService = new ExportService();

        //public ActionResult Index(string id)
        //{
        //    var yml = ImportExportService.Export(id);
        //    return Content(yml, "text/xml");
        //}
    }
}

Benefit.Web/Controllers/ScheduleController.cs
using Benefit.Domain.DataAccess;
using Benefit.Domain.Models;
using Benefit.Services.Domain;
using Benefit.Web.Filters;
using Benefit.Web.Helpers;
using System;
using System.IO;
using System.Linq;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Mvc;
using Benefit.Services.Import;

namespace Benefit.Web.Controllers
{
    [CustomKeyAuth]
    public class ScheduleController : Controller
    {
        public ActionResult ProcessImportTasks()
        {
            using (var db = new ApplicationDbContext())
            {
                var importTasks =
                db.ExportImports
                    .Include(entry => entry.Seller)
                    .Include(entry => entry.Seller.MappedCategories)
                    .Where(entry => entry.IsActive && entry.SyncType != SyncType.YmlExport && entry.SyncType != SyncType.YmlExport).ToList();
                Task.Run(() =>
                {
                    foreach (var importTask in importTasks)
                    {
                        if (importTask.LastSync.HasValue && (DateTime.UtcNow - importTask.LastSync.Value).TotalDays < importTask.SyncPeriod)
                        {
                            continue;
                        }
                        ImportServiceFactory.GetImportServiceInstance(importTask.SyncType).Import(importTask.Id);
                    }
                });
            }
            return Content("Ok");
        }
        public ActionResult GenerateSellerReport(int? year = null, int? month = null, string sellerId = null)
        {
            var sellerReportService = new SellerReportService();
            year = year ?? DateTime.Now.Year;
            month = month ?? (DateTime.Now.Month - 1 == 0 ? 12 : DateTime.Now.Month - 1);
            var startDate = new DateTime(year.Value, month.Value, 1, 0, 0, 0);
            var endDate = new DateTime(year.Value, month.Value, DateTime.DaysInMonth(year.Value, month.Value), 23, 59, 59);
            var originalDirectory = AppDomain.CurrentDomain.BaseDirectory.Replace(@"bin\Debug\", string.Empty);
            var reportsPath = Path.Combine(originalDirectory, "Reports");
            using (var db = new ApplicationDbContext())
            {
                var sellerIds = db.Orders
                    .Where(entry => entry.Time > startDate && entry.Time < endDate)
                    .Select(entry => entry.SellerId).Distinct();
                if (sellerId != null)
                {
                    sellerIds = sellerIds.Where(entry => entry == sellerId);
                }
                foreach (var seller_id in sellerIds)
                {
                    if (db.SellerReports.Any(entry => entry.SellerId == seller_id && entry.Month == month && entry.Year == year))
                        continue;
                    var bytes = sellerReportService.GenerateSellerReport(seller_id, startDate, endDate);
                    var reportPath = Path.Combine(reportsPath, seller_id);
                    if (!Directory.Exists(reportPath))
                    {
                        Directory.CreateDirectory(reportPath);
                    }
                    System.IO.File.WriteAllBytes(
                        Path.Combine(reportPath, string.Format("{0}-{1}-{2}.xls", year.Value, month.Value, DateTime.Now.ToString("yyyyMMddhhmm"))), bytes);
                    var sellerReport = new SellerReport()
                    {
                        Date = DateTime.Now,
                        FileUrl = string.Format("{0}-{1}-{2}.xls", year.Value, month.Value, DateTime.Now.ToString("yyyyMMddhhmm")),
                        Id = Guid.NewGuid().ToString(),
                        SellerId = seller_id,
                        Month = month.Value,
                        Year = year.Value
                    };
                    db.SellerReports.Add(sellerReport);
                }
                db.SaveChanges();
            }
            return Content("Ok");
        }
        public ActionResult GenerateExportFiles(string exportId = null)
        {
            var exportService = new ExportService();
            var originalDirectory = AppDomain.CurrentDomain.BaseDirectory.Replace(@"bin\Debug\", string.Empty);
            using (var db = new ApplicationDbContext())
            {
                var exports = db.ExportImports.Where(entry => entry.SyncType == SyncType.YmlExport || entry.SyncType == SyncType.YmlExportEpicentr || entry.SyncType == SyncType.YmlExportProm).ToList();
                if (exportId != null)
                {
                    exports = exports.Where(entry => entry.Id == exportId).ToList();
                }
                foreach (var export in exports)
                {
                    var destPath = Path.Combine(originalDirectory, "Export", export.Name);
                    var isExists = Directory.Exists(destPath);
                    if (!isExists)
                    {
                        Directory.CreateDirectory(destPath);
                    }
                    destPath = Path.Combine(destPath, "index.xml");
                    if (exportService.Export(export.Id, destPath) == null)
                    {
                        return Content("Export file was not generated");
                    }
                }
            }
            return Content("Export files generated");
        }

        public ActionResult GenerateSiteMap()
        {
            var siteMapHelper = new SiteMapHelper();
            siteMapHelper.Generate(Url, Request.Url.Scheme + "://" + Request.Url.Host);
            return Content("Ok");
        }
    }
}

Benefit.Web/Areas/Admin/Views/ImportExport/Exports.cshtml
@model System.Collections.Generic.List<Benefit.Domain.Models.ExportImport>

@{
    ViewBag.Title = "Експорти";
}
@section scripts
{
    <script>
        $(function () {
            $("#new-export").click(function () {
                $(".modal").modal();
            });
        });
    </script>
}
<h2>Експорти</h2>

<p>
    <a href="#" id="new-export" class="btn btn-info">Створити новий</a>
</p>
<table class="table">
    <tr>
        <th>
            Назва
        </th>
        <th>
            Посилання
        </th>
        <th>
            Дії
        </th>
    </tr>

    @foreach (var export in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => export.Name)
            </td>
            <td>
                @{
                    var link = string.Format("{0}://{1}/Export/{2}/index.xml", Request.Url.Scheme, Request.Url.Host, export.Name);
                }
                <a href="@link" target="_blank">@link</a>
            </td>
            <td>
                @Html.ActionLink("Згенерувати", "GenerateExportFiles", "Schedule", new { key = "15e77370-9268-4007-a00d-49aca257b7d6", exportId = export.Id, area = string.Empty }, new { @class = "btn btn-success" })
                |
                @Html.ActionLink("Видалити", "DeleteExport", new { id = export.Id }, new { onclick = "return confirm('Ви впевнені? Також видаляться звязані назви категорій і звязки товарів з експортом. ');" })
            </td>
        </tr>
    }
</table>
<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title pull-left">Новий експорт</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Html.BeginForm("CreateOrUpdateExport", "ImportExport"))
            {
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right">* Назва</label>
                            <div class="col-sm-9">
                                @Html.TextBox("Name", null, new { placeholder = "Назва" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right">Тип</label>
                            <div class="col-sm-9">
                                <select name="SyncType">
                                    <option value="YmlExport">YML Rozetka</option>
                                    <option value="YmlExportEpicentr">YML Epicentr</option>
                                    <option value="YmlExportProm">YML Prom.ua</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Зберегти</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
                </div>
            }
        </div>
    </div>
</div>

Benefit.Web/Areas/Admin/Views/ImportExport/Index.cshtml
@using Benefit.Domain.Models
@model Benefit.Domain.Models.Seller

@{
    ViewBag.Title = "Імпорт/Експорт";
}
@section scripts
{
    <script>
        var launchImportUrl = apiUrl + '@Url.Action("ProcessImport", "Import", new {sellerId = Model.Id, area = string.Empty})'.replace("Benefit.Web","");
        var importStatusUrl = '@Url.Action("GetImportTaskStatus", "ImportExport", new {sellerId = Model.Id })';
        var getLinkFormUrl = '@Url.Action("GetImportLinkForm", "ImportExport")';
        var intervalId;
        const ImportStatusEnum = { "error": 0, "success": 1, "pending": 2 };
        Object.freeze(ImportStatusEnum)

        $(function () {
            $(".fn-add-import-file").click(function (e) {
                var btn = $(this);
                btn.attr("disabled", "disabled");
                var number = parseInt($(this).attr("data-link-count"));
                var url = getLinkFormUrl + "?number=" + number;
                $.get(url, function (data) {
                    btn.before(data);
                    btn.attr("data-link-count", ++number);
                    btn.removeAttr("disabled");
                });
            });

            $("body").on("click", ".fn-remove-link-form", function (e) {
                e.preventDefault();
                $(this).parents(".form-group").remove();
            });

            $(".fn-launch-import").click(function () {
                var btn = $(this);
                var importType = btn.attr("data-import-type");
                $(this).attr("disabled", "disabled");
                $("#importing-process").show();
                $.get(launchImportUrl + "&type=" + importType,
                    function (data) {
                        if (data.error) {
                            btn.removeAttr("disabled");
                            flashMessage(data.error, true, true);
                            $("#importing-process").hide();
                        } else {
                            flashMessage(data.message, false, true);
                            intervalId = setInterval(function f() {
                                $.get(importStatusUrl + "&type=" + importType,
                                    function (data) {
                                        if (data.status != ImportStatusEnum.pending) {
                                            $("#importing-process").hide();
                                            clearInterval(intervalId);
                                            location.reload();
                                        }
                                    });
                            }, 10000);
                        }
                    });
            });
        });
    </script>
}
<div id="importing-process" style="display: none;">
    <div class="loader"></div>
    <h2 style="color: red;">Відбувається процес імпорту</h2>
</div>
<h2>Імпорт\Експорт</h2>
<div class="tabbable">
    <ul class="nav nav-tabs" id="myTab">
        <li class="active">
            <a data-toggle="tab" href="#prom">
                Yml
            </a>
        </li>
        <li>
            <a data-toggle="tab" href="#excel">
                Excel
            </a>
        </li>
        <li>
            <a data-toggle="tab" href="#1ccommerceml">
                1C Commerce ML
            </a>
        </li>
        <li>
            <a data-toggle="tab" href="#gbs">
                GBS Market
            </a>
        </li>
        <li>
            <a data-toggle="tab" href="#firebird">
                Firebird SQL
            </a>
        </li>
    </ul>
    <div class="tab-content">
        <div id="prom" class="tab-pane in active">
            @Html.Action("GetImportForm", new { syncType = SyncType.Yml })
        </div>
        <div id="firebird" class="tab-pane">
            @Html.Action("GetImportForm", new { syncType = SyncType.FirebirdSql })
        </div>
        <div id="gbs" class="tab-pane">
            @Html.Action("GetImportForm", new { syncType = SyncType.Gbs })
        </div>
        <div id="excel" class="tab-pane">
            <div>
                <h3 class="red" id="warning-message">Імпорт з файлу зробить неактивними всі товари з бази, яких немає у файлі імпорту.</h3>
                <h2 class="underlined">
                    Excel
                </h2>
                <p>1) Завантажте Excel файл (import.xls) та зображення (в архіві ZIP)</p>
                @using (Html.BeginForm("UploadExcelFile", "ImportExport", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <p>
                        import.xls <input type="file" name="import" accept=".xlsx, .xls" value="Файл імпорту" />
                    </p>
                    <p>
                        images.zip <input type="file" name="images" accept=".zip" value="Архів зображень" />
                    </p>
                    <input type="hidden" name="sellerUrlName" value="@Model.UrlName" />
                    <br />
                    <input type="submit" value="Завантажити" class="btn btn-default" />
                }
                <p>
                    2) Натисніть кнопку
                    <button type="button" class="btn btn-success fn-launch-import" data-import-type="Excel">Excel Import</button>
                </p>
            </div>
        </div>
        <div id="1ccommerceml" class="tab-pane">
            @Html.Action("GetImportForm", new { syncType = SyncType.OneCCommerceMl })
        </div>
    </div>
</div>

Benefit.Web/Areas/Admin/Views/ImportExport/Status.cshtml
@using Benefit.Domain.Models
@using Benefit.Common.Extensions
@model IEnumerable<ExportImport>
@{
    ViewBag.Title = "Статус імпорту постачальників";
}

<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    Назва
                </th>
                <th>
                    Статус
                </th>
                <th>
                    Тип
                </th>
                <th>
                    Останній час імпорту
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var task in Model)
            {
                var className = "";
                if (task.Status != null)
                {
                    switch (task.Status)
                    {
                        case ImportStatus.Success:
                            className = "bg-success";
                            break;
                        case ImportStatus.Error:
                            className = "bg-danger";
                            break;
                    }
                }
                <tr class="@className">
                    <td>
                        @task.Seller.Name
                    </td>
                    <td>
                        @if (task.IsActive)
                        {
                            <div class="icon-check-sign green"></div>
                        }
                        else
                        {
                            <div class="icon-ban-circle red"></div>
                        }
                    </td>
                    <td>
                        @task.SyncType.ToString()
                    </td>
                    <td>
                        @if (task.LastSync.HasValue)
                        {
                            <span>@task.LastSync.Value.ToLocalDateTimeWithFormat()</span>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Benefit.Web/Areas/Admin/Views/ImportExport/_ImportForm.cshtml
@using Benefit.Common.Extensions
@using Benefit.Domain.Models
@model ExportImport

@using (Html.BeginForm("CreateOrUpdate", "ImportExport"))
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.SellerId)
    @Html.HiddenFor(model => model.SyncType)

    <div class="form-group">
        <label class="control-label col-md-2" for="IsActive">Статус</label>
        <div class="col-md-10">
            @Html.CheckBoxFor(m => m.IsActive)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2" for="IsImport">В процессі обробки</label>
        <div class="col-md-10">
            @Html.CheckBoxFor(m => m.IsImport) (має бути неактивно)
        </div>
    </div>
    <div class="form-group">
        @if (Model.SyncType != SyncType.FirebirdSql)
        {
            <label class="control-label col-md-2" for="FileUrl">URL</label>
        }
        else
        {
            <label class="control-label col-md-2" for="FileUrl">Connection String</label>
        }
        <div class="col-md-10">
            @if (Model.SyncType != SyncType.YmlExport)
            {
                @Html.TextBoxFor(model => model.FileUrl, new { @class = "width-90" })
            }
            else
            {
                @Html.TextBoxFor(model => model.FileUrl, new { @class = "width-90", @readonly = "readonly" })
            }
            @Html.ValidationMessageFor(model => model.FileUrl)
            <br />
        </div>
    </div>
    @for (var i = 0; i < Model.Links.Count; i++)
    {
        @Html.Partial("_LinkForm", new KeyValuePair<int, string>(i, Model.Links.ElementAt(i).Url))
    }
    <a href="#" class="fn-add-import-file" data-link-count="0" style="float:right; margin-right: 10%;">
        <i class="icon-plus"></i> Додати файл імпорту
    </a>

    <div class="form-group">
        <label class="control-label col-md-2" for="IsActive">Валюта за замовчуванням</label>
        <div class="col-md-10">
            @Html.DropDownList("DefaultCurrencyId", null, new { @class = "col-sm-3" })
        </div>
    </div>

    @if (Model.SyncType != SyncType.YmlExport)
    {
        <div class="form-group">
            <label class="control-label col-md-2" for="SyncPeriod">Частота оновлення</label>
            <div class="col-md-10">
                @Html.DropDownList("SyncPeriod", null, new { @class = "col-md-3" })
            </div>
        </div>

        if (Model.LastUpdateStatus.HasValue && Model.LastSync != null)
        {
            <div class="form-group">
                <label class="control-label col-md-2">Статус останнього оновлення</label>
                <div class="col-md-10">
                    @if (Model.LastUpdateStatus.GetValueOrDefault(false))
                    {
                        <i class="icon icon-check green bigger-200"></i>
                    }
                    else
                    {
                        <i class="icon icon-remove red bigger-200"></i>
                        <div>Помилка: @Model.LastUpdateMessage</div>
                    }
                    <div>
                        Час: @Model.LastSync.Value.ToLocalDateTimeWithFormat()
                    </div>
                    <div>
                        Наступне оновлення відбудеться: @Model.LastSync.Value.AddDays(Model.SyncPeriod).ToLocalDateTimeWithFormat()
                    </div>
                </div>
            </div>
        }
        else if (Model.Id != null && Model.IsActive)
        {
            <div class="col-md-offset-2">
                Наступне оновлення відбудеться: @DateTime.UtcNow.ToLocalTime().EndOfDay().AddHours(3).ToLocalDateTimeWithFormat()
            </div>
        }
    }

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Зберегти" class="btn btn-info" />
            @*<button type="button" class="margin-left-30 btn btn-success fn-launch-import" data-import-type="@Model.SyncType.ToString()">Запустити</button>*@
        </div>
    </div>
</div>
}