Benefit.Web/Areas/Admin/Controllers/NotificationsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Benefit.Common.Constants;
using Benefit.Domain.DataAccess;
using Benefit.Domain.Models;

namespace Benefit.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = DomainConstants.AdminRoleName + ", " + DomainConstants.SellerRoleName + ", " + DomainConstants.SellerModeratorRoleName)]
    public class NotificationsController : Controller
    {
        public ActionResult Index()
        {
            using (var db = new ApplicationDbContext())
            {
                var channels = db.NotificationChannels.Where(entry => entry.SellerId == Seller.CurrentAuthorizedSellerId).ToList();
                return View(channels);
            }
        }

        public ActionResult Create(NotificationChannelType channelType)
        {
            return PartialView("Create", channelType);
        }

        public ActionResult CreateOrUpdate(NotificationChannel model)
        {
            using (var db = new ApplicationDbContext())
            {
                if (model.Address != null)
                {
                    model.SellerId = Seller.CurrentAuthorizedSellerId;
                    model.Id = Guid.NewGuid().ToString();
                    db.NotificationChannels.Add(model);
                    db.SaveChanges();
                    TempData["SuccessMessage"] = "Канал сповіщення збереженно";
                    return RedirectToAction("Index");
                }
                TempData["ErrorMessage"] = "Невірне значення";
                return RedirectToAction("Index");
            }
        }

        public ActionResult Delete(string id)
        {
            using (var db = new ApplicationDbContext())
            {
                var channel = db.NotificationChannels.Find(id);
                db.NotificationChannels.Remove(channel);
                db.SaveChanges();
                TempData["SuccessMessage"] = "Канал сповіщення видалено";
                return RedirectToAction("Index");
            }
        }
    }
}

Benefit.Web/Controllers/EmailController.cs
using System.Web.Mvc;
using Benefit.DataTransfer.ViewModels;
using Benefit.Domain.Models;
using Benefit.Services;

namespace Benefit.Web.Controllers
{
    public class EmailController : Controller
    {
        EmailService EmailService = new EmailService();

        [HttpGet]
        public ActionResult SellerApplication()
        {
            return PartialView("_SellerApplication");
        }

        [HttpPost]
        public ActionResult SendFacebookAccoutJoinRequest(string facebookAccount)
        {
            EmailService.SendEmail(EmailService.BenefitInfoEmail, string.Format("Постачальник: {0}, фейсбук: {1}", Seller.CurrentAuthorizedSellerName, facebookAccount),
                "Запит на підключення фейсбук сповіщень");
            return new HttpStatusCodeResult(200);
        }
	}
}

Benefit.Web/Areas/Admin/Views/Notifications/Create.cshtml
@model Benefit.Domain.Models.NotificationChannelType

<div class="modal-dialog">
    <div class="modal-content">
        @using (Html.BeginForm("CreateOrUpdate", "Notifications"))
        {
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Нове сповіщення @Model.ToString()</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-3">Назва</div>
                    <div class="col-md-9">
                        <input type="text" name="Name" class="col-md-8"/>
                    </div>
                </div>
                <div class="row margin-top-10">
                    <div class="col-md-3">Значення</div>
                    <div class="col-md-9">
                        <input type="hidden" name="ChannelType" value="@Model" />
                        <input type="@Model.ToString()" name="Address" class="col-md-8" />
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success">Зберегти</button>
            </div>
        }
    </div>
</div>

Benefit.Web/Areas/Admin/Views/Notifications/Index.cshtml
@using Benefit.Domain.Models
@model IEnumerable<NotificationChannel>

@{
    ViewBag.Title = "Сповіщення";
}
@section scripts
{
    <script>
        var fbJoinUrl = '@Url.Action("SendFacebookAccoutJoinRequest","Email", new { area = string.Empty })';

        $(function () {
            $(".add-notification").click(function (e) {
                e.preventDefault();
                var addNotificationUrl = '@Url.Action("Create")';
                addNotificationUrl += "?channelType=" + $(this).attr("data-channel-type");
                $("#modal-container").load(addNotificationUrl, function () {
                    $("#modal-container").modal("show");
                });
            });

            $("#send-fb-acc").click(function () {
                var fbAcc = $("#facebook-account").val();
                if (fbAcc === "") {
                    alert("Поле Facebook акаунту має бути заповнено");
                    return;
                }
                var model = {
                    facebookAccount: fbAcc
                }
                $.post(fbJoinUrl, model, function () {
                    flashMessage("Повідомлення було відправлено");
                    $("#facebook-account").val("");
                });
            });
        });
    </script>
}
<div id="modal-container" class="modal fade in"></div>

<div class="row">
    <div class="col-sm-5">
        <h3 class="row header smaller lighter red">
            <span class="col-sm-8">
                <i class="fa fa-telegram"></i>
                Telegram
            </span>
            <span class="col-sm-4">
                <a class="btn btn-success btn-xs pull-right add-notification" data-channel-type="Telegram">
                    <i class="icon-plus bigger-110 icon-only"></i>
                </a>
            </span>
        </h3>
        <div>
            <p>
                Для того, щоб підключити Telegram повідомлення про нові замовлення пройдіть таку нескладну процедуру
            </p>
            <p>
                1) Відправте повідомлення чат боту <a href="tg://resolve?domain=BenefitCompanyBot">BenefitCompanyBot</a>
                з текстом /start
            </p>
            <p>
                2) 1 - для сповіщень про замовлення
            </p>
            <p>
                3) ідентифікатор постачальника @Seller.CurrentAuthorizedSellerId
            </p>
            @if (Model.Where(entry => entry.ChannelType == NotificationChannelType.Telegram).Any())
            {
                <div id="accordion" class="accordion-style1 panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                    <i class="ace-icon fa fa-angle-down bigger-110" data-icon-hide="ace-icon fa fa-angle-down" data-icon-show="ace-icon fa fa-angle-right"></i>
                                    &nbsp;Підключені чати сповіщення
                                </a>
                            </h4>
                        </div>

                        <div class="panel-collapse collapse" id="collapseOne">
                            <div class="panel-body">
                                @foreach (var telegram in Model.Where(entry => entry.ChannelType == NotificationChannelType.Telegram))
                                {
                                    <div class="well well-sm clearfix">
                                        <span class="col-sm-11">
                                            @if (!string.IsNullOrEmpty(telegram.Name))
                                            {
                                                <span>@telegram.Name -</span>
                                            }
                                            <span>@telegram.Address</span>
                                        </span>
                                        <a onclick="return confirm('Ви впевненні?')" href="@Url.Action("Delete", new { id = telegram.Id })" class="pull-right">
                                            <i class="icon-remove red"></i>
                                        </a>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="col-sm-2">
    </div>
    <div class="col-sm-5">
        <h3 class="row header smaller lighter blue">
            <span class="col-sm-8">
                <i class="icon-facebook-sign"></i>
                Facebook
            </span>
            <span class="col-sm-4">
                <a class="btn btn-success btn-xs pull-right add-notification" data-channel-type="Facebook">
                    <i class="icon-plus bigger-110 icon-only"></i>
                </a>
            </span>
        </h3>
        <div>
            <p>
                Для того, щоб підключити фейсбук повідомлення про нові замовлення пройдіть таку нескладну процедуру
            </p>
            <p>
                1. Лайкнути нашу Facebook сторінку <br />
                <!-- FB Widget -->
                <div class="social_block fb hide_on_tablet">
                    <div id="fb-root"></div>
                    <script>
                        (function (d, s, id) {
                            var js, fjs = d.getElementsByTagName(s)[0];
                            if (d.getElementById(id)) return;
                            js = d.createElement(s);
                            js.id = id;
                            js.src = "//connect.facebook.net/ru_RU/sdk.js#xfbml=1&version=v2.7&appId=635571649935665";
                            fjs.parentNode.insertBefore(js, fjs);
                        }(document, 'script', 'facebook-jssdk'));
                    </script>
                    <div class="fb-page" data-href="https://www.facebook.com/https.benefit.ua/" data-width="225" data-height="300" data-small-header="false" data-adapt-container-width="false" data-hide-cover="false" data-show-facepile="true">
                        <blockquote cite="https://www.facebook.com/https.benefit.ua/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/https.benefit.ua/">Global Benefit Network Company</a></blockquote>
                    </div>
                </div>
            </p>
            <p>
                2. Відправити нам посилання на свій Facebook акаунт <br />
                <input type="text" id="facebook-account" class="col-md-6" />
                <button type="button" class="btn btn-info btn-sm" id="send-fb-acc">Відправити</button>
            </p>
            <p>
                3. Відправте повідомлення на нашу Facebook сторінку
                <a href="https://www.facebook.com/https.benefit.ua/" target="_blank">https://www.facebook.com/https.benefit.ua/</a>
                з цим текстом: @Seller.CurrentAuthorizedSellerId
            </p>
            @if (Model.Where(entry => entry.ChannelType == NotificationChannelType.Facebook).Any())
            {
                <div id="accordion2" class="accordion-style1 panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse2">
                                    <i class="ace-icon fa fa-angle-down bigger-110" data-icon-hide="ace-icon fa fa-angle-down" data-icon-show="ace-icon fa fa-angle-right"></i>
                                    &nbsp;Підключені чати сповіщення
                                </a>
                            </h4>
                        </div>

                        <div class="panel-collapse collapse" id="collapse2">
                            <div class="panel-body">
                                @foreach (var fb in Model.Where(entry => entry.ChannelType == NotificationChannelType.Facebook))
                                {
                                    <div class="well well-sm clearfix">
                                        <span class="col-sm-11">
                                            @if (!string.IsNullOrEmpty(fb.Name))
                                            {
                                                <span>@fb.Name -</span>
                                            }
                                            <span>@fb.Address</span>
                                        </span>
                                        <a onclick="return confirm('Ви впевненні?')" href="@Url.Action("Delete", new { id = fb.Id })" class="pull-right">
                                            <i class="icon-remove red"></i>
                                        </a>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@*<div class="row">
        <div class="col-sm-5">
            <h3 class="row header smaller lighter purple">
                <span class="col-sm-8">
                    <i class="icon-phone-sign"></i>
                    SMS
                </span>
                <span class="col-sm-4">
                    <a class="btn btn-success btn-xs pull-right add-notification" data-channel-type="Phone">
                        <i class="icon-plus bigger-110 icon-only"></i>
                    </a>
                </span>
            </h3>
            <div>
                @foreach (var phone in Model.Where(entry => entry.ChannelType == NotificationChannelType.Phone))
                {
                    <div class="well well-sm clearfix">
                        <span class="col-sm-11">
                            @if (!string.IsNullOrEmpty(phone.Name))
                            {
                                <span>@phone.Name -</span>
                            }
                            <span>@phone.Address</span>
                        </span>
                        <a onclick="return confirm('Ви впевненні?')" href="@Url.Action("Delete", new {id = phone.Id})" class="pull-right">
                            <i class="icon-remove red"></i>
                        </a>
                    </div>
                }
            </div>
        </div>
        <div class="col-sm-2">
        </div>
        <div class="col-sm-5">
            <h3 class="row header smaller lighter orange">
                <span class="col-sm-8">
                    <i class="icon-envelope-alt"></i>
                    Email
                </span>
                <span class="col-sm-4">
                    <a class="btn btn-success btn-xs pull-right add-notification" data-channel-type="Email">
                        <i class="icon-plus bigger-110 icon-only"></i>
                    </a>
                </span>
            </h3>
            <div>
                @foreach (var email in Model.Where(entry => entry.ChannelType == NotificationChannelType.Email))
                {
                    <div class="well well-sm clearfix">
                        <span class="col-sm-11">
                            @if (!string.IsNullOrEmpty(email.Name))
                            {
                                <span>@email.Name -</span>
                            }
                            <span>@email.Address</span>
                        </span>
                        <a onclick="return confirm('Ви впевненні?')" href="@Url.Action("Delete", new { id = email.Id })" class="pull-right">
                            <i class="icon-remove red"></i>
                        </a>
                    </div>
                }
            </div>
        </div>

    </div>*@